const SignInFormData = [
    {
        id: crypto.randomUUID(),
        label: "First name",
        type: "text",
        name: "fname",
        placeholder: "",
        required: true,
        errorMessage: "Please enter your first name",
    },
    {
        id: crypto.randomUUID(),
        label: "Last name",
        type: "text",
        name: "lname",
        placeholder: "",
        required: true,
        errorMessage: "Please enter your last name",
    },
    {
        id: crypto.randomUUID(),
        label: "Phone number",
        type: "tel",
        name: "pnumber",
        placeholder: "",
        defaultValue: "+880",
        required: true,
        errorMessage: "Phone number must be 11 digit long",
    },
    {
        id: crypto.randomUUID(),
        label: "Email",
        type: "email",
        name: "email",
        placeholder: "",
        required: true,
        errorMessage: "Please provide a properly formatted email address",
    },
    {
        id: crypto.randomUUID(),
        label: "Create password",
        type: "password",
        name: "password",
        placeholder: "",
        patttern: "^[a-zA-Z0-9]{6,}$",
        required: true,
        errorMessage: "Password must be at least 6 character long",
    },
];
export default SignInFormData;
